### ISSUE TITLE
Please add document_ids to the check.yaml schema

### ISSUE THREAD

**Issue by Nialld** [onfido/onfido-openapi-spec#5]
ive added it manually to the generated php file to test and it appears to be working, not sure if there is anything else i should be looking at?

```
document_ids:
        description: An array of document ids.
        type: array
        items:
          type: string
```
